/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fp.onion;

import java.io.File;

import com.google.common.util.concurrent.AtomicDouble;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.Button;
import javafx.scene.control.ColorPicker;
import javafx.scene.control.Slider;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Pane;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.stage.DirectoryChooser;
import javafx.stage.Stage;

public class App extends Application {

    private ImageWatch image_watch;
    private ColorPicker keyColor_picker;
    private Color keyColor;
    private Canvas current;
    private Canvas previous;
    private GraphicsContext cgc;
    private GraphicsContext pgc;
    private ImageProcessor ip;
    private AtomicDouble keyDelta;
    private AtomicDouble transIntensity;

    public App() {
        this.image_watch = new ImageWatch(this);
        this.current = new Canvas(1024, 768);
        this.previous = new Canvas(1024, 768);
        this.cgc = this.current.getGraphicsContext2D();
        this.pgc = this.previous.getGraphicsContext2D();
        this.ip = new ImageProcessor(this.cgc, this.pgc);
        this.keyDelta = new AtomicDouble(0.11);
        this.transIntensity = new AtomicDouble(0.2);
    }

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage) {
        BorderPane root = new BorderPane();

        StackPane centerStack = new StackPane();
        root.setCenter(centerStack);

        HBox botBar = new HBox();
        root.setBottom(botBar);

        centerStack.getChildren().add(previous);
        centerStack.getChildren().add(current);

        //ip.enqueueCurrent(ScriptBuilder.getChromaScript("/home/laowl/Pictures/neat.png", Color.GREEN, 0.1) ) ;

        Button selectDir_btn = new Button("Select");
        selectDir_btn.setOnMouseClicked( (event -> {
            DirectoryChooser dirChooser = new DirectoryChooser();
            if (!image_watch.isWatching()) {
                File r = dirChooser.showDialog(selectDir_btn.getScene().getWindow());
                if (r != null) {
                    image_watch.startWatch(r.toPath());
                    selectDir_btn.setDisable(true);
                }
            }
        }));
        botBar.getChildren().add(selectDir_btn);

        keyColor_picker = new ColorPicker(Color.GREEN);
        keyColor_picker.setOnAction( (event) -> {
            keyColor = keyColor_picker.getValue();
        });
        botBar.getChildren().add(keyColor_picker);

        Slider delta_sldr = new Slider();
        delta_sldr.setValue(0.11);
        delta_sldr.setMin(0.0);
        delta_sldr.setMax(1.0);
        delta_sldr.setBlockIncrement(0.05);
        delta_sldr.adjustValue(0.01);
        delta_sldr.setMajorTickUnit(0.20);
        delta_sldr.setMinorTickCount(4);
        delta_sldr.setShowTickLabels(true);
        delta_sldr.setShowTickMarks(true);
        delta_sldr.valueProperty().addListener( (ov, old_val, new_val) -> keyDelta.set(new_val.doubleValue()) );
        botBar.getChildren().add(delta_sldr);

        Slider trans_sldr = new Slider();
        trans_sldr.setValue(0.2);
        trans_sldr.setMin(0.0);
        trans_sldr.setMax(1.0);
        trans_sldr.setBlockIncrement(0.05);
        trans_sldr.adjustValue(0.01);
        trans_sldr.setMajorTickUnit(0.20);
        trans_sldr.setMinorTickCount(4);
        trans_sldr.setShowTickLabels(true);
        trans_sldr.setShowTickMarks(true);
        trans_sldr.valueProperty().addListener( (ov, old_val, new_val) -> transIntensity.set(new_val.doubleValue()) );
        botBar.getChildren().add(trans_sldr);

        stage.setTitle("fp-onion");
        Scene scene = new Scene(root, 1024, 800);
        stage.setScene(scene);
        stage.show();
    }

    public void setCurrent(String file) {
        this.ip.enqueueCurrent(ScriptBuilder.getChromaScript(file, keyColor, keyDelta.get()));
    }

    public void setPrevious(String file) {
        this.ip.enqueuePrevious( ScriptBuilder.getTransparencyScript(ScriptBuilder.getChromaScript(file, keyColor, keyDelta.get()), transIntensity.get()) );
    }

    @Override
    public void stop(){
        System.out.println("Stage is closing");
        if (image_watch.isWatching()) {
            image_watch.stop();
        }
        ip.close();
    }

}
